export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED";

export const SORT_BY_PRICE_ASC = "SORT_BY_PRICE_ASC";
export const SORT_BY_PRICE_DESC = "SORT_BY_PRICE_DESC";

export const SORT_BY_BRAND_ASC = "SORT_BY_BRAND_ASC";
export const SORT_BY_BRAND_DESC = "SORT_BY_BRAND_DESC";

export const SORT_BY_MOST_POPULAR = "SORT_BY_MOST_POPULAR";
export const SORT_BY_BRAND_TOP_RATED = "SORT_BY_BRAND_TOP_RATED";



